version: '2'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    volumes: 
      - zoo-data:/zookeeper/data
    networks:
      - sync_debezium_network
  kafka:  
    container_name: kafka
    hostname: kafka
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    depends_on:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
     - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://${IP_CONFIG_COMPUTER}:9092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
     - KAFKA_LOG_RETENTION_MS=259200000 # 3 days
     - KAFKA_SEGMENT_INDEX_BYTES=104857600 # Xác định kích thước tối đa của chỉ mục segment log trên Kafka broker
     - KAFKA_MESSAGE_MAX_BYTES=20971520 # Xác định kích thước tối đa của một message có thể được Kafka broker chấp nhận
    volumes: 
      - kafka-data:/kafka/data
    networks:
      - sync_debezium_network
  kafka-connect:
    container_name: kafka-connect
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    depends_on:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=debezium_configs
     - OFFSET_STORAGE_TOPIC=debezium_offsets
     - STATUS_STORAGE_TOPIC=debezium_statuses
     - OFFSET_STORAGE_REPLICATION_FACTOR=1
     - OFFSET_STORAGE_PARTITIONS=1

     - CONNECT_PRODUCER_MAX_REQUEST_SIZE=5242880 # Giới hạn kích thước tối đa của một request gửi từ Kafka Producer (Debezium Connect)
     - CONNECT_CONSUMER_FETCH_MAX_BYTES=5242880 # Xác định kích thước tối đa của một lần fetch từ Kafka Consumer (Debezium Connect).
     - CONNECT_MAX_BATCH_SIZE=500 # Số lượng bản ghi tối đa mà Debezium có thể xử lý trong một batch trước khi gửi sang Kafka.
     - CONNECT_MAX_QUEUE_SIZE=1000 # Giới hạn số lượng bản ghi tối đa trong queue trước khi chúng được gửi từ Debezium sang Kafka.
     - CONNECT_MAX_REQUEST_SIZE=5242880 # Giới hạn kích thước tối đa của một request từ Kafka Connect gửi sang Kafka Broker.
    networks:
      - sync_debezium_network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      auth.type: LOGIN_FORM
      SPRING_SECURITY_USER_NAME: ${SPRING_SECURITY_USER_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_USER_PASSWORD}
    networks:
      - sync_debezium_network
networks:
  sync_debezium_network:
    driver: bridge
volumes: 
  kafka-data:
  zoo-data:
